# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'multioskeleton' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for multioskeleton
  pod 'Fabric'
  pod 'Crashlytics'
end

target 'multioskeleton-Test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for multioskeleton-Test

end
